{
    "openapi": "3.0.0",
    "info": {
        "title": "Multi API",
        "description": "Uma API em Node usando typescript para o projeto Multi.",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:4000",
            "description": "Local server"
        }
    ],
    "paths": {
        "/produtos": {
            "get": {
                "summary": "Listar todos os produtos no Banco de Dados",
                "description": "Retorna um Array de produtos",
                "tags": [
                    "Produtos"
                ],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Produto"
                                    }
                                },
                                "examples": {
                                    "produto":{
                                        "value":{
                                            "_id": "(ID gerado pelo banco)",
                                            "nome": "Sala de Festas",
                                            "descricao": "Uma sala equipada luzes piscantes e sons altos.",
                                            "categoria": "Espaços",
                                            "disponibilidade": [
                                                {
                                                    "data": "2025-10-05",
                                                    "horario": "09:00-11:00",
                                                    "_id": "(ID gerado pelo banco)"
                                                },
                                                {
                                                    "data": "2027-10-06",
                                                    "horario": "13:00-15:00",
                                                    "_id": "(ID gerado pelo banco)"
                                                }
                                            ],
                                            "preco": 1500
                                        }
        
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }

            },
            "post": {
                "summary": "Cadastro de um novo produto no Banco de Dados",
                "description": "Cria um novo produto",
                "tags": [
                    "Produtos"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Produto"
                            },
                            "examples": {
                                "produto": {
                                    "value": {
                                        "nome": "Sala de Festas",
                                        "descricao": "Uma sala equipada luzes piscantes e sons altos.",
                                        "categoria": "Espaços",
                                        "disponibilidade": [
                                            {
                                                "data": "2025-10-05",
                                                "horario": "09:00-11:00"
                                            },
                                            {
                                                "data": "2027-10-06",
                                                "horario": "13:00-15:00"
                                            }
                                        ],
                                        "preco": 1500
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Produto criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Produto"
                                },
                                "examples": {
                                    "produto": {
                                        "value": {
                                            "_id": "(ID gerado pelo banco)",
                                            "nome": "Sala de Festas",
                                            "descricao": "Uma sala equipada luzes piscantes e sons altos.",
                                            "categoria": "Espaços",
                                            "disponibilidade": [
                                                {
                                                    "data": "2025-10-05",
                                                    "horario": "09:00-11:00",
                                                    "_id": "(ID gerado pelo banco)"
                                                },
                                                {
                                                    "data": "2027-10-06",
                                                    "horario": "13:00-15:00",
                                                    "_id": "(ID gerado pelo banco)"
                                                }
                                            ],
                                            "preco": 1500
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Parametro Invalido"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            } 
        },
        "/produtos/nomeOuId": {
            "get": {
                "summary": "Listar um produto específico no Banco de Dados",
                "description": "Retorna um produto",
                "tags": [
                    "Produtos"
                ],
                "parameters": [
                    {
                        "name": "nome",
                        "in": "query"
                    },
                    {
                        "name": "id",
                        "in": "query",
                        "description": "ID do produto"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Produto"
                                },
                                "examples": {
                                    "produto":{
                                        "value":{
                                            "_id": "(ID gerado pelo banco)",
                                            "nome": "Sala de Festas",
                                            "descricao": "Uma sala equipada luzes piscantes e sons altos.",
                                            "categoria": "Espaços",
                                            "disponibilidade": [
                                                {
                                                    "data": "2025-10-05",
                                                    "horario": "09:00-11:00",
                                                    "_id": "(ID gerado pelo banco)"
                                                },
                                                {
                                                    "data": "2027-10-06",
                                                    "horario": "13:00-15:00",
                                                    "_id": "(ID gerado pelo banco)"
                                                }
                                            ],
                                            "preco": 1500
                                        }
        
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Parametro Invalido"
                    },
                    "404": {
                        "description": "Produto não encontrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/produtos/{id}": {
            "delete": {
                "summary": "Deletar um produto específico no Banco de Dados",
                "description": "Deleta um produto",
                "tags": [
                    "Produtos"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do produto"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produto deletado com sucesso"
                    },
                    "400": {
                        "description": "Parametro Invalido"
                    },
                    "404": {
                        "description": "Produto não encontrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Produto":{
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "objectID"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "categoria":{
                        "type":"string",
                        "enum": ["Espaços", "Serviços", "Equipamento"]
                    },
                    "disponibilidade":{
                        "type":"array",
                        "items":{
                            "type":"object",
                            "properties": {
                                "data": {
                                    "type": "date"
                                },
                                "horario": {
                                    "type": "string"
                                },
                                "_id": {
                                    "type": "objectID"
                                }
                            }
                        }
                    },
                    "preco": {
                        "type": "number"
                    }
                }
            }
        }
    }
}